// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testJudgementPartiesAs(t *testing.T) {
	t.Parallel()

	query := JudgementPartiesAs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testJudgementPartiesAsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := JudgementPartiesAs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testJudgementPartiesAsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := JudgementPartiesAs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := JudgementPartiesAs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testJudgementPartiesAsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := JudgementPartiesASlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := JudgementPartiesAs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testJudgementPartiesAsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := JudgementPartiesAExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if JudgementPartiesA exists: %s", err)
	}
	if !e {
		t.Errorf("Expected JudgementPartiesAExists to return true, but got false.")
	}
}

func testJudgementPartiesAsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	judgementPartiesAFound, err := FindJudgementPartiesA(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if judgementPartiesAFound == nil {
		t.Error("want a record, got nil")
	}
}

func testJudgementPartiesAsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = JudgementPartiesAs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testJudgementPartiesAsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := JudgementPartiesAs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testJudgementPartiesAsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	judgementPartiesAOne := &JudgementPartiesA{}
	judgementPartiesATwo := &JudgementPartiesA{}
	if err = randomize.Struct(seed, judgementPartiesAOne, judgementPartiesADBTypes, false, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}
	if err = randomize.Struct(seed, judgementPartiesATwo, judgementPartiesADBTypes, false, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = judgementPartiesAOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = judgementPartiesATwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := JudgementPartiesAs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testJudgementPartiesAsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	judgementPartiesAOne := &JudgementPartiesA{}
	judgementPartiesATwo := &JudgementPartiesA{}
	if err = randomize.Struct(seed, judgementPartiesAOne, judgementPartiesADBTypes, false, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}
	if err = randomize.Struct(seed, judgementPartiesATwo, judgementPartiesADBTypes, false, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = judgementPartiesAOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = judgementPartiesATwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := JudgementPartiesAs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testJudgementPartiesAsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := JudgementPartiesAs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testJudgementPartiesAsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(judgementPartiesAColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := JudgementPartiesAs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testJudgementPartiesAsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testJudgementPartiesAsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := JudgementPartiesASlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testJudgementPartiesAsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := JudgementPartiesAs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	judgementPartiesADBTypes = map[string]string{`ID`: `character varying`, `PartyANames`: `character varying`}
	_                        = bytes.MinRead
)

func testJudgementPartiesAsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(judgementPartiesAPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(judgementPartiesAAllColumns) == len(judgementPartiesAPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := JudgementPartiesAs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testJudgementPartiesAsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(judgementPartiesAAllColumns) == len(judgementPartiesAPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPartiesA{}
	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := JudgementPartiesAs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, judgementPartiesADBTypes, true, judgementPartiesAPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(judgementPartiesAAllColumns, judgementPartiesAPrimaryKeyColumns) {
		fields = judgementPartiesAAllColumns
	} else {
		fields = strmangle.SetComplement(
			judgementPartiesAAllColumns,
			judgementPartiesAPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := JudgementPartiesASlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testJudgementPartiesAsUpsert(t *testing.T) {
	t.Parallel()

	if len(judgementPartiesAAllColumns) == len(judgementPartiesAPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := JudgementPartiesA{}
	if err = randomize.Struct(seed, &o, judgementPartiesADBTypes, true); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert JudgementPartiesA: %s", err)
	}

	count, err := JudgementPartiesAs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, judgementPartiesADBTypes, false, judgementPartiesAPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize JudgementPartiesA struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert JudgementPartiesA: %s", err)
	}

	count, err = JudgementPartiesAs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
