// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testJudgementPrinciples(t *testing.T) {
	t.Parallel()

	query := JudgementPrinciples()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testJudgementPrinciplesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := JudgementPrinciples().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testJudgementPrinciplesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := JudgementPrinciples().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := JudgementPrinciples().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testJudgementPrinciplesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := JudgementPrincipleSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := JudgementPrinciples().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testJudgementPrinciplesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := JudgementPrincipleExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if JudgementPrinciple exists: %s", err)
	}
	if !e {
		t.Errorf("Expected JudgementPrincipleExists to return true, but got false.")
	}
}

func testJudgementPrinciplesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	judgementPrincipleFound, err := FindJudgementPrinciple(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if judgementPrincipleFound == nil {
		t.Error("want a record, got nil")
	}
}

func testJudgementPrinciplesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = JudgementPrinciples().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testJudgementPrinciplesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := JudgementPrinciples().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testJudgementPrinciplesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	judgementPrincipleOne := &JudgementPrinciple{}
	judgementPrincipleTwo := &JudgementPrinciple{}
	if err = randomize.Struct(seed, judgementPrincipleOne, judgementPrincipleDBTypes, false, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}
	if err = randomize.Struct(seed, judgementPrincipleTwo, judgementPrincipleDBTypes, false, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = judgementPrincipleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = judgementPrincipleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := JudgementPrinciples().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testJudgementPrinciplesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	judgementPrincipleOne := &JudgementPrinciple{}
	judgementPrincipleTwo := &JudgementPrinciple{}
	if err = randomize.Struct(seed, judgementPrincipleOne, judgementPrincipleDBTypes, false, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}
	if err = randomize.Struct(seed, judgementPrincipleTwo, judgementPrincipleDBTypes, false, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = judgementPrincipleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = judgementPrincipleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := JudgementPrinciples().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testJudgementPrinciplesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := JudgementPrinciples().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testJudgementPrinciplesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(judgementPrincipleColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := JudgementPrinciples().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testJudgementPrinciplesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testJudgementPrinciplesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := JudgementPrincipleSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testJudgementPrinciplesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := JudgementPrinciples().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	judgementPrincipleDBTypes = map[string]string{`ID`: `integer`, `PrincipleId`: `integer`, `SuitNo`: `character varying`}
	_                         = bytes.MinRead
)

func testJudgementPrinciplesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(judgementPrinciplePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(judgementPrincipleAllColumns) == len(judgementPrinciplePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := JudgementPrinciples().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrinciplePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testJudgementPrinciplesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(judgementPrincipleAllColumns) == len(judgementPrinciplePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &JudgementPrinciple{}
	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrincipleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := JudgementPrinciples().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, judgementPrincipleDBTypes, true, judgementPrinciplePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(judgementPrincipleAllColumns, judgementPrinciplePrimaryKeyColumns) {
		fields = judgementPrincipleAllColumns
	} else {
		fields = strmangle.SetComplement(
			judgementPrincipleAllColumns,
			judgementPrinciplePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := JudgementPrincipleSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testJudgementPrinciplesUpsert(t *testing.T) {
	t.Parallel()

	if len(judgementPrincipleAllColumns) == len(judgementPrinciplePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := JudgementPrinciple{}
	if err = randomize.Struct(seed, &o, judgementPrincipleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert JudgementPrinciple: %s", err)
	}

	count, err := JudgementPrinciples().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, judgementPrincipleDBTypes, false, judgementPrinciplePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize JudgementPrinciple struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert JudgementPrinciple: %s", err)
	}

	count, err = JudgementPrinciples().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
