// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testKeywordRankings(t *testing.T) {
	t.Parallel()

	query := KeywordRankings()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testKeywordRankingsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := KeywordRankings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testKeywordRankingsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := KeywordRankings().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := KeywordRankings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testKeywordRankingsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := KeywordRankingSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := KeywordRankings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testKeywordRankingsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := KeywordRankingExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if KeywordRanking exists: %s", err)
	}
	if !e {
		t.Errorf("Expected KeywordRankingExists to return true, but got false.")
	}
}

func testKeywordRankingsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	keywordRankingFound, err := FindKeywordRanking(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if keywordRankingFound == nil {
		t.Error("want a record, got nil")
	}
}

func testKeywordRankingsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = KeywordRankings().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testKeywordRankingsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := KeywordRankings().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testKeywordRankingsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	keywordRankingOne := &KeywordRanking{}
	keywordRankingTwo := &KeywordRanking{}
	if err = randomize.Struct(seed, keywordRankingOne, keywordRankingDBTypes, false, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}
	if err = randomize.Struct(seed, keywordRankingTwo, keywordRankingDBTypes, false, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = keywordRankingOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = keywordRankingTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := KeywordRankings().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testKeywordRankingsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	keywordRankingOne := &KeywordRanking{}
	keywordRankingTwo := &KeywordRanking{}
	if err = randomize.Struct(seed, keywordRankingOne, keywordRankingDBTypes, false, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}
	if err = randomize.Struct(seed, keywordRankingTwo, keywordRankingDBTypes, false, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = keywordRankingOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = keywordRankingTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := KeywordRankings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testKeywordRankingsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := KeywordRankings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testKeywordRankingsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(keywordRankingColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := KeywordRankings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testKeywordRankingsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testKeywordRankingsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := KeywordRankingSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testKeywordRankingsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := KeywordRankings().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	keywordRankingDBTypes = map[string]string{`ID`: `integer`, `KeywordID`: `bigint`, `Rank`: `bigint`, `IndexID`: `bigint`, `SuitNo`: `text`, `Title`: `text`, `Header`: `text`, `Court`: `text`, `Judgedate`: `text`, `Subbody`: `text`, `Type`: `integer`}
	_                     = bytes.MinRead
)

func testKeywordRankingsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(keywordRankingPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(keywordRankingAllColumns) == len(keywordRankingPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := KeywordRankings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testKeywordRankingsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(keywordRankingAllColumns) == len(keywordRankingPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &KeywordRanking{}
	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := KeywordRankings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, keywordRankingDBTypes, true, keywordRankingPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(keywordRankingAllColumns, keywordRankingPrimaryKeyColumns) {
		fields = keywordRankingAllColumns
	} else {
		fields = strmangle.SetComplement(
			keywordRankingAllColumns,
			keywordRankingPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := KeywordRankingSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testKeywordRankingsUpsert(t *testing.T) {
	t.Parallel()

	if len(keywordRankingAllColumns) == len(keywordRankingPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := KeywordRanking{}
	if err = randomize.Struct(seed, &o, keywordRankingDBTypes, true); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert KeywordRanking: %s", err)
	}

	count, err := KeywordRankings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, keywordRankingDBTypes, false, keywordRankingPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize KeywordRanking struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert KeywordRanking: %s", err)
	}

	count, err = KeywordRankings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
