// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testLawOfFedScheds(t *testing.T) {
	t.Parallel()

	query := LawOfFedScheds()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testLawOfFedSchedsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := LawOfFedScheds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLawOfFedSchedsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := LawOfFedScheds().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := LawOfFedScheds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLawOfFedSchedsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := LawOfFedSchedSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := LawOfFedScheds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLawOfFedSchedsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := LawOfFedSchedExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if LawOfFedSched exists: %s", err)
	}
	if !e {
		t.Errorf("Expected LawOfFedSchedExists to return true, but got false.")
	}
}

func testLawOfFedSchedsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	lawOfFedSchedFound, err := FindLawOfFedSched(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if lawOfFedSchedFound == nil {
		t.Error("want a record, got nil")
	}
}

func testLawOfFedSchedsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = LawOfFedScheds().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testLawOfFedSchedsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := LawOfFedScheds().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testLawOfFedSchedsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	lawOfFedSchedOne := &LawOfFedSched{}
	lawOfFedSchedTwo := &LawOfFedSched{}
	if err = randomize.Struct(seed, lawOfFedSchedOne, lawOfFedSchedDBTypes, false, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}
	if err = randomize.Struct(seed, lawOfFedSchedTwo, lawOfFedSchedDBTypes, false, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = lawOfFedSchedOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = lawOfFedSchedTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := LawOfFedScheds().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testLawOfFedSchedsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	lawOfFedSchedOne := &LawOfFedSched{}
	lawOfFedSchedTwo := &LawOfFedSched{}
	if err = randomize.Struct(seed, lawOfFedSchedOne, lawOfFedSchedDBTypes, false, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}
	if err = randomize.Struct(seed, lawOfFedSchedTwo, lawOfFedSchedDBTypes, false, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = lawOfFedSchedOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = lawOfFedSchedTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := LawOfFedScheds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testLawOfFedSchedsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := LawOfFedScheds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testLawOfFedSchedsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(lawOfFedSchedColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := LawOfFedScheds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testLawOfFedSchedsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testLawOfFedSchedsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := LawOfFedSchedSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testLawOfFedSchedsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := LawOfFedScheds().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	lawOfFedSchedDBTypes = map[string]string{`ID`: `integer`, `SchedHeader`: `character varying`, `SchedBody`: `text`, `LawId`: `integer`}
	_                    = bytes.MinRead
)

func testLawOfFedSchedsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(lawOfFedSchedPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(lawOfFedSchedAllColumns) == len(lawOfFedSchedPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := LawOfFedScheds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testLawOfFedSchedsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(lawOfFedSchedAllColumns) == len(lawOfFedSchedPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSched{}
	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := LawOfFedScheds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, lawOfFedSchedDBTypes, true, lawOfFedSchedPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(lawOfFedSchedAllColumns, lawOfFedSchedPrimaryKeyColumns) {
		fields = lawOfFedSchedAllColumns
	} else {
		fields = strmangle.SetComplement(
			lawOfFedSchedAllColumns,
			lawOfFedSchedPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := LawOfFedSchedSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testLawOfFedSchedsUpsert(t *testing.T) {
	t.Parallel()

	if len(lawOfFedSchedAllColumns) == len(lawOfFedSchedPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := LawOfFedSched{}
	if err = randomize.Struct(seed, &o, lawOfFedSchedDBTypes, true); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert LawOfFedSched: %s", err)
	}

	count, err := LawOfFedScheds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, lawOfFedSchedDBTypes, false, lawOfFedSchedPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSched struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert LawOfFedSched: %s", err)
	}

	count, err = LawOfFedScheds().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
