// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testLawOfFedSections(t *testing.T) {
	t.Parallel()

	query := LawOfFedSections()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testLawOfFedSectionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := LawOfFedSections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLawOfFedSectionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := LawOfFedSections().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := LawOfFedSections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLawOfFedSectionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := LawOfFedSectionSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := LawOfFedSections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLawOfFedSectionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := LawOfFedSectionExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if LawOfFedSection exists: %s", err)
	}
	if !e {
		t.Errorf("Expected LawOfFedSectionExists to return true, but got false.")
	}
}

func testLawOfFedSectionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	lawOfFedSectionFound, err := FindLawOfFedSection(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if lawOfFedSectionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testLawOfFedSectionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = LawOfFedSections().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testLawOfFedSectionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := LawOfFedSections().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testLawOfFedSectionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	lawOfFedSectionOne := &LawOfFedSection{}
	lawOfFedSectionTwo := &LawOfFedSection{}
	if err = randomize.Struct(seed, lawOfFedSectionOne, lawOfFedSectionDBTypes, false, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}
	if err = randomize.Struct(seed, lawOfFedSectionTwo, lawOfFedSectionDBTypes, false, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = lawOfFedSectionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = lawOfFedSectionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := LawOfFedSections().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testLawOfFedSectionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	lawOfFedSectionOne := &LawOfFedSection{}
	lawOfFedSectionTwo := &LawOfFedSection{}
	if err = randomize.Struct(seed, lawOfFedSectionOne, lawOfFedSectionDBTypes, false, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}
	if err = randomize.Struct(seed, lawOfFedSectionTwo, lawOfFedSectionDBTypes, false, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = lawOfFedSectionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = lawOfFedSectionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := LawOfFedSections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testLawOfFedSectionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := LawOfFedSections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testLawOfFedSectionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(lawOfFedSectionColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := LawOfFedSections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testLawOfFedSectionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testLawOfFedSectionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := LawOfFedSectionSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testLawOfFedSectionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := LawOfFedSections().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	lawOfFedSectionDBTypes = map[string]string{`ID`: `integer`, `SectionHeader`: `character varying`, `SectionBody`: `text`, `LawId`: `integer`, `PartId`: `integer`}
	_                      = bytes.MinRead
)

func testLawOfFedSectionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(lawOfFedSectionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(lawOfFedSectionAllColumns) == len(lawOfFedSectionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := LawOfFedSections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testLawOfFedSectionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(lawOfFedSectionAllColumns) == len(lawOfFedSectionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &LawOfFedSection{}
	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := LawOfFedSections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, lawOfFedSectionDBTypes, true, lawOfFedSectionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(lawOfFedSectionAllColumns, lawOfFedSectionPrimaryKeyColumns) {
		fields = lawOfFedSectionAllColumns
	} else {
		fields = strmangle.SetComplement(
			lawOfFedSectionAllColumns,
			lawOfFedSectionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := LawOfFedSectionSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testLawOfFedSectionsUpsert(t *testing.T) {
	t.Parallel()

	if len(lawOfFedSectionAllColumns) == len(lawOfFedSectionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := LawOfFedSection{}
	if err = randomize.Struct(seed, &o, lawOfFedSectionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert LawOfFedSection: %s", err)
	}

	count, err := LawOfFedSections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, lawOfFedSectionDBTypes, false, lawOfFedSectionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize LawOfFedSection struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert LawOfFedSection: %s", err)
	}

	count, err = LawOfFedSections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
