// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// NoteRating is an object representing the database table.
type NoteRating struct {
	ID     string      `boil:"Id" json:"Id" toml:"Id" yaml:"Id"`
	NoteId null.String `boil:"NoteId" json:"NoteId,omitempty" toml:"NoteId" yaml:"NoteId,omitempty"`
	UserId int64       `boil:"UserId" json:"UserId" toml:"UserId" yaml:"UserId"`
	Rating int         `boil:"Rating" json:"Rating" toml:"Rating" yaml:"Rating"`

	R *noteRatingR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L noteRatingL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var NoteRatingColumns = struct {
	ID     string
	NoteId string
	UserId string
	Rating string
}{
	ID:     "Id",
	NoteId: "NoteId",
	UserId: "UserId",
	Rating: "Rating",
}

// Generated where

var NoteRatingWhere = struct {
	ID     whereHelperstring
	NoteId whereHelpernull_String
	UserId whereHelperint64
	Rating whereHelperint
}{
	ID:     whereHelperstring{field: "\"NoteRatings\".\"Id\""},
	NoteId: whereHelpernull_String{field: "\"NoteRatings\".\"NoteId\""},
	UserId: whereHelperint64{field: "\"NoteRatings\".\"UserId\""},
	Rating: whereHelperint{field: "\"NoteRatings\".\"Rating\""},
}

// NoteRatingRels is where relationship names are stored.
var NoteRatingRels = struct {
}{}

// noteRatingR is where relationships are stored.
type noteRatingR struct {
}

// NewStruct creates a new relationship struct
func (*noteRatingR) NewStruct() *noteRatingR {
	return &noteRatingR{}
}

// noteRatingL is where Load methods for each relationship are stored.
type noteRatingL struct{}

var (
	noteRatingAllColumns            = []string{"Id", "NoteId", "UserId", "Rating"}
	noteRatingColumnsWithoutDefault = []string{"Id", "NoteId", "UserId", "Rating"}
	noteRatingColumnsWithDefault    = []string{}
	noteRatingPrimaryKeyColumns     = []string{"Id"}
)

type (
	// NoteRatingSlice is an alias for a slice of pointers to NoteRating.
	// This should generally be used opposed to []NoteRating.
	NoteRatingSlice []*NoteRating

	noteRatingQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	noteRatingType                 = reflect.TypeOf(&NoteRating{})
	noteRatingMapping              = queries.MakeStructMapping(noteRatingType)
	noteRatingPrimaryKeyMapping, _ = queries.BindMapping(noteRatingType, noteRatingMapping, noteRatingPrimaryKeyColumns)
	noteRatingInsertCacheMut       sync.RWMutex
	noteRatingInsertCache          = make(map[string]insertCache)
	noteRatingUpdateCacheMut       sync.RWMutex
	noteRatingUpdateCache          = make(map[string]updateCache)
	noteRatingUpsertCacheMut       sync.RWMutex
	noteRatingUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single noteRating record from the query.
func (q noteRatingQuery) One(ctx context.Context, exec boil.ContextExecutor) (*NoteRating, error) {
	o := &NoteRating{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for NoteRatings")
	}

	return o, nil
}

// All returns all NoteRating records from the query.
func (q noteRatingQuery) All(ctx context.Context, exec boil.ContextExecutor) (NoteRatingSlice, error) {
	var o []*NoteRating

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to NoteRating slice")
	}

	return o, nil
}

// Count returns the count of all NoteRating records in the query.
func (q noteRatingQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count NoteRatings rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q noteRatingQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if NoteRatings exists")
	}

	return count > 0, nil
}

// NoteRatings retrieves all the records using an executor.
func NoteRatings(mods ...qm.QueryMod) noteRatingQuery {
	mods = append(mods, qm.From("\"NoteRatings\""))
	return noteRatingQuery{NewQuery(mods...)}
}

// FindNoteRating retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindNoteRating(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*NoteRating, error) {
	noteRatingObj := &NoteRating{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"NoteRatings\" where \"Id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, noteRatingObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from NoteRatings")
	}

	return noteRatingObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *NoteRating) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no NoteRatings provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(noteRatingColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	noteRatingInsertCacheMut.RLock()
	cache, cached := noteRatingInsertCache[key]
	noteRatingInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			noteRatingAllColumns,
			noteRatingColumnsWithDefault,
			noteRatingColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(noteRatingType, noteRatingMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(noteRatingType, noteRatingMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"NoteRatings\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"NoteRatings\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into NoteRatings")
	}

	if !cached {
		noteRatingInsertCacheMut.Lock()
		noteRatingInsertCache[key] = cache
		noteRatingInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the NoteRating.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *NoteRating) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	noteRatingUpdateCacheMut.RLock()
	cache, cached := noteRatingUpdateCache[key]
	noteRatingUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			noteRatingAllColumns,
			noteRatingPrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return 0, errors.New("models: unable to update NoteRatings, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"NoteRatings\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, noteRatingPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(noteRatingType, noteRatingMapping, append(wl, noteRatingPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update NoteRatings row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for NoteRatings")
	}

	if !cached {
		noteRatingUpdateCacheMut.Lock()
		noteRatingUpdateCache[key] = cache
		noteRatingUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q noteRatingQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for NoteRatings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for NoteRatings")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o NoteRatingSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), noteRatingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"NoteRatings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, noteRatingPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in noteRating slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all noteRating")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *NoteRating) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no NoteRatings provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(noteRatingColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	noteRatingUpsertCacheMut.RLock()
	cache, cached := noteRatingUpsertCache[key]
	noteRatingUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			noteRatingAllColumns,
			noteRatingColumnsWithDefault,
			noteRatingColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			noteRatingAllColumns,
			noteRatingPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert NoteRatings, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(noteRatingPrimaryKeyColumns))
			copy(conflict, noteRatingPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"NoteRatings\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(noteRatingType, noteRatingMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(noteRatingType, noteRatingMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert NoteRatings")
	}

	if !cached {
		noteRatingUpsertCacheMut.Lock()
		noteRatingUpsertCache[key] = cache
		noteRatingUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single NoteRating record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *NoteRating) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no NoteRating provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), noteRatingPrimaryKeyMapping)
	sql := "DELETE FROM \"NoteRatings\" WHERE \"Id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from NoteRatings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for NoteRatings")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q noteRatingQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no noteRatingQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from NoteRatings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for NoteRatings")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o NoteRatingSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), noteRatingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"NoteRatings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, noteRatingPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from noteRating slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for NoteRatings")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *NoteRating) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindNoteRating(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *NoteRatingSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := NoteRatingSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), noteRatingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"NoteRatings\".* FROM \"NoteRatings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, noteRatingPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in NoteRatingSlice")
	}

	*o = slice

	return nil
}

// NoteRatingExists checks if the NoteRating row exists.
func NoteRatingExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"NoteRatings\" where \"Id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if NoteRatings exists")
	}

	return exists, nil
}
