// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// NoteComment is an object representing the database table.
type NoteComment struct {
	ID        string      `boil:"Id" json:"Id" toml:"Id" yaml:"Id"`
	NoteId    null.String `boil:"NoteId" json:"NoteId,omitempty" toml:"NoteId" yaml:"NoteId,omitempty"`
	CreatorId int64       `boil:"CreatorId" json:"CreatorId" toml:"CreatorId" yaml:"CreatorId"`
	Body      null.String `boil:"Body" json:"Body,omitempty" toml:"Body" yaml:"Body,omitempty"`
	CreatedAt time.Time   `boil:"CreatedAt" json:"CreatedAt" toml:"CreatedAt" yaml:"CreatedAt"`

	R *noteCommentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L noteCommentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var NoteCommentColumns = struct {
	ID        string
	NoteId    string
	CreatorId string
	Body      string
	CreatedAt string
}{
	ID:        "Id",
	NoteId:    "NoteId",
	CreatorId: "CreatorId",
	Body:      "Body",
	CreatedAt: "CreatedAt",
}

// Generated where

var NoteCommentWhere = struct {
	ID        whereHelperstring
	NoteId    whereHelpernull_String
	CreatorId whereHelperint64
	Body      whereHelpernull_String
	CreatedAt whereHelpertime_Time
}{
	ID:        whereHelperstring{field: "\"NoteComments\".\"Id\""},
	NoteId:    whereHelpernull_String{field: "\"NoteComments\".\"NoteId\""},
	CreatorId: whereHelperint64{field: "\"NoteComments\".\"CreatorId\""},
	Body:      whereHelpernull_String{field: "\"NoteComments\".\"Body\""},
	CreatedAt: whereHelpertime_Time{field: "\"NoteComments\".\"CreatedAt\""},
}

// NoteCommentRels is where relationship names are stored.
var NoteCommentRels = struct {
}{}

// noteCommentR is where relationships are stored.
type noteCommentR struct {
}

// NewStruct creates a new relationship struct
func (*noteCommentR) NewStruct() *noteCommentR {
	return &noteCommentR{}
}

// noteCommentL is where Load methods for each relationship are stored.
type noteCommentL struct{}

var (
	noteCommentAllColumns            = []string{"Id", "NoteId", "CreatorId", "Body", "CreatedAt"}
	noteCommentColumnsWithoutDefault = []string{"Id", "NoteId", "CreatorId", "Body", "CreatedAt"}
	noteCommentColumnsWithDefault    = []string{}
	noteCommentPrimaryKeyColumns     = []string{"Id"}
)

type (
	// NoteCommentSlice is an alias for a slice of pointers to NoteComment.
	// This should generally be used opposed to []NoteComment.
	NoteCommentSlice []*NoteComment

	noteCommentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	noteCommentType                 = reflect.TypeOf(&NoteComment{})
	noteCommentMapping              = queries.MakeStructMapping(noteCommentType)
	noteCommentPrimaryKeyMapping, _ = queries.BindMapping(noteCommentType, noteCommentMapping, noteCommentPrimaryKeyColumns)
	noteCommentInsertCacheMut       sync.RWMutex
	noteCommentInsertCache          = make(map[string]insertCache)
	noteCommentUpdateCacheMut       sync.RWMutex
	noteCommentUpdateCache          = make(map[string]updateCache)
	noteCommentUpsertCacheMut       sync.RWMutex
	noteCommentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single noteComment record from the query.
func (q noteCommentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*NoteComment, error) {
	o := &NoteComment{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for NoteComments")
	}

	return o, nil
}

// All returns all NoteComment records from the query.
func (q noteCommentQuery) All(ctx context.Context, exec boil.ContextExecutor) (NoteCommentSlice, error) {
	var o []*NoteComment

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to NoteComment slice")
	}

	return o, nil
}

// Count returns the count of all NoteComment records in the query.
func (q noteCommentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count NoteComments rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q noteCommentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if NoteComments exists")
	}

	return count > 0, nil
}

// NoteComments retrieves all the records using an executor.
func NoteComments(mods ...qm.QueryMod) noteCommentQuery {
	mods = append(mods, qm.From("\"NoteComments\""))
	return noteCommentQuery{NewQuery(mods...)}
}

// FindNoteComment retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindNoteComment(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*NoteComment, error) {
	noteCommentObj := &NoteComment{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"NoteComments\" where \"Id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, noteCommentObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from NoteComments")
	}

	return noteCommentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *NoteComment) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no NoteComments provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(noteCommentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	noteCommentInsertCacheMut.RLock()
	cache, cached := noteCommentInsertCache[key]
	noteCommentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			noteCommentAllColumns,
			noteCommentColumnsWithDefault,
			noteCommentColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(noteCommentType, noteCommentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(noteCommentType, noteCommentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"NoteComments\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"NoteComments\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into NoteComments")
	}

	if !cached {
		noteCommentInsertCacheMut.Lock()
		noteCommentInsertCache[key] = cache
		noteCommentInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the NoteComment.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *NoteComment) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	noteCommentUpdateCacheMut.RLock()
	cache, cached := noteCommentUpdateCache[key]
	noteCommentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			noteCommentAllColumns,
			noteCommentPrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return 0, errors.New("models: unable to update NoteComments, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"NoteComments\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, noteCommentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(noteCommentType, noteCommentMapping, append(wl, noteCommentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update NoteComments row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for NoteComments")
	}

	if !cached {
		noteCommentUpdateCacheMut.Lock()
		noteCommentUpdateCache[key] = cache
		noteCommentUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q noteCommentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for NoteComments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for NoteComments")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o NoteCommentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), noteCommentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"NoteComments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, noteCommentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in noteComment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all noteComment")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *NoteComment) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no NoteComments provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(noteCommentColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	noteCommentUpsertCacheMut.RLock()
	cache, cached := noteCommentUpsertCache[key]
	noteCommentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			noteCommentAllColumns,
			noteCommentColumnsWithDefault,
			noteCommentColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			noteCommentAllColumns,
			noteCommentPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert NoteComments, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(noteCommentPrimaryKeyColumns))
			copy(conflict, noteCommentPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"NoteComments\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(noteCommentType, noteCommentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(noteCommentType, noteCommentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert NoteComments")
	}

	if !cached {
		noteCommentUpsertCacheMut.Lock()
		noteCommentUpsertCache[key] = cache
		noteCommentUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single NoteComment record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *NoteComment) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no NoteComment provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), noteCommentPrimaryKeyMapping)
	sql := "DELETE FROM \"NoteComments\" WHERE \"Id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from NoteComments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for NoteComments")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q noteCommentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no noteCommentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from NoteComments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for NoteComments")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o NoteCommentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), noteCommentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"NoteComments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, noteCommentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from noteComment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for NoteComments")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *NoteComment) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindNoteComment(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *NoteCommentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := NoteCommentSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), noteCommentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"NoteComments\".* FROM \"NoteComments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, noteCommentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in NoteCommentSlice")
	}

	*o = slice

	return nil
}

// NoteCommentExists checks if the NoteComment row exists.
func NoteCommentExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"NoteComments\" where \"Id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if NoteComments exists")
	}

	return exists, nil
}
