// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testNoteRatings(t *testing.T) {
	t.Parallel()

	query := NoteRatings()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testNoteRatingsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NoteRatings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNoteRatingsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := NoteRatings().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NoteRatings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNoteRatingsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NoteRatingSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NoteRatings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNoteRatingsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := NoteRatingExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if NoteRating exists: %s", err)
	}
	if !e {
		t.Errorf("Expected NoteRatingExists to return true, but got false.")
	}
}

func testNoteRatingsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	noteRatingFound, err := FindNoteRating(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if noteRatingFound == nil {
		t.Error("want a record, got nil")
	}
}

func testNoteRatingsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = NoteRatings().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testNoteRatingsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := NoteRatings().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testNoteRatingsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	noteRatingOne := &NoteRating{}
	noteRatingTwo := &NoteRating{}
	if err = randomize.Struct(seed, noteRatingOne, noteRatingDBTypes, false, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}
	if err = randomize.Struct(seed, noteRatingTwo, noteRatingDBTypes, false, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = noteRatingOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = noteRatingTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := NoteRatings().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testNoteRatingsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	noteRatingOne := &NoteRating{}
	noteRatingTwo := &NoteRating{}
	if err = randomize.Struct(seed, noteRatingOne, noteRatingDBTypes, false, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}
	if err = randomize.Struct(seed, noteRatingTwo, noteRatingDBTypes, false, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = noteRatingOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = noteRatingTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NoteRatings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testNoteRatingsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NoteRatings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNoteRatingsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(noteRatingColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := NoteRatings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNoteRatingsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNoteRatingsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NoteRatingSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNoteRatingsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := NoteRatings().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	noteRatingDBTypes = map[string]string{`ID`: `text`, `NoteId`: `text`, `UserId`: `bigint`, `Rating`: `integer`}
	_                 = bytes.MinRead
)

func testNoteRatingsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(noteRatingPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(noteRatingAllColumns) == len(noteRatingPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NoteRatings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testNoteRatingsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(noteRatingAllColumns) == len(noteRatingPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &NoteRating{}
	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NoteRatings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, noteRatingDBTypes, true, noteRatingPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(noteRatingAllColumns, noteRatingPrimaryKeyColumns) {
		fields = noteRatingAllColumns
	} else {
		fields = strmangle.SetComplement(
			noteRatingAllColumns,
			noteRatingPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := NoteRatingSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testNoteRatingsUpsert(t *testing.T) {
	t.Parallel()

	if len(noteRatingAllColumns) == len(noteRatingPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := NoteRating{}
	if err = randomize.Struct(seed, &o, noteRatingDBTypes, true); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert NoteRating: %s", err)
	}

	count, err := NoteRatings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, noteRatingDBTypes, false, noteRatingPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NoteRating struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert NoteRating: %s", err)
	}

	count, err = NoteRatings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
