// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testNoteComments(t *testing.T) {
	t.Parallel()

	query := NoteComments()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testNoteCommentsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NoteComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNoteCommentsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := NoteComments().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NoteComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNoteCommentsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NoteCommentSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NoteComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNoteCommentsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := NoteCommentExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if NoteComment exists: %s", err)
	}
	if !e {
		t.Errorf("Expected NoteCommentExists to return true, but got false.")
	}
}

func testNoteCommentsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	noteCommentFound, err := FindNoteComment(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if noteCommentFound == nil {
		t.Error("want a record, got nil")
	}
}

func testNoteCommentsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = NoteComments().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testNoteCommentsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := NoteComments().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testNoteCommentsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	noteCommentOne := &NoteComment{}
	noteCommentTwo := &NoteComment{}
	if err = randomize.Struct(seed, noteCommentOne, noteCommentDBTypes, false, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}
	if err = randomize.Struct(seed, noteCommentTwo, noteCommentDBTypes, false, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = noteCommentOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = noteCommentTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := NoteComments().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testNoteCommentsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	noteCommentOne := &NoteComment{}
	noteCommentTwo := &NoteComment{}
	if err = randomize.Struct(seed, noteCommentOne, noteCommentDBTypes, false, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}
	if err = randomize.Struct(seed, noteCommentTwo, noteCommentDBTypes, false, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = noteCommentOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = noteCommentTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NoteComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testNoteCommentsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NoteComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNoteCommentsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(noteCommentColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := NoteComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNoteCommentsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNoteCommentsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NoteCommentSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNoteCommentsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := NoteComments().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	noteCommentDBTypes = map[string]string{`ID`: `text`, `NoteId`: `text`, `CreatorId`: `bigint`, `Body`: `text`, `CreatedAt`: `timestamp without time zone`}
	_                  = bytes.MinRead
)

func testNoteCommentsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(noteCommentPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(noteCommentAllColumns) == len(noteCommentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NoteComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testNoteCommentsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(noteCommentAllColumns) == len(noteCommentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &NoteComment{}
	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NoteComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, noteCommentDBTypes, true, noteCommentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(noteCommentAllColumns, noteCommentPrimaryKeyColumns) {
		fields = noteCommentAllColumns
	} else {
		fields = strmangle.SetComplement(
			noteCommentAllColumns,
			noteCommentPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := NoteCommentSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testNoteCommentsUpsert(t *testing.T) {
	t.Parallel()

	if len(noteCommentAllColumns) == len(noteCommentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := NoteComment{}
	if err = randomize.Struct(seed, &o, noteCommentDBTypes, true); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert NoteComment: %s", err)
	}

	count, err := NoteComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, noteCommentDBTypes, false, noteCommentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NoteComment struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert NoteComment: %s", err)
	}

	count, err = NoteComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
