// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testOtpLicenses(t *testing.T) {
	t.Parallel()

	query := OtpLicenses()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testOtpLicensesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OtpLicenses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOtpLicensesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := OtpLicenses().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OtpLicenses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOtpLicensesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OtpLicenseSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OtpLicenses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOtpLicensesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := OtpLicenseExists(ctx, tx, o.Rowid)
	if err != nil {
		t.Errorf("Unable to check if OtpLicense exists: %s", err)
	}
	if !e {
		t.Errorf("Expected OtpLicenseExists to return true, but got false.")
	}
}

func testOtpLicensesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	otpLicenseFound, err := FindOtpLicense(ctx, tx, o.Rowid)
	if err != nil {
		t.Error(err)
	}

	if otpLicenseFound == nil {
		t.Error("want a record, got nil")
	}
}

func testOtpLicensesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = OtpLicenses().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testOtpLicensesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := OtpLicenses().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testOtpLicensesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	otpLicenseOne := &OtpLicense{}
	otpLicenseTwo := &OtpLicense{}
	if err = randomize.Struct(seed, otpLicenseOne, otpLicenseDBTypes, false, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}
	if err = randomize.Struct(seed, otpLicenseTwo, otpLicenseDBTypes, false, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = otpLicenseOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = otpLicenseTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OtpLicenses().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testOtpLicensesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	otpLicenseOne := &OtpLicense{}
	otpLicenseTwo := &OtpLicense{}
	if err = randomize.Struct(seed, otpLicenseOne, otpLicenseDBTypes, false, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}
	if err = randomize.Struct(seed, otpLicenseTwo, otpLicenseDBTypes, false, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = otpLicenseOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = otpLicenseTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OtpLicenses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testOtpLicensesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OtpLicenses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOtpLicensesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(otpLicenseColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := OtpLicenses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOtpLicensesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOtpLicensesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OtpLicenseSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOtpLicensesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OtpLicenses().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	otpLicenseDBTypes = map[string]string{`Rowid`: `integer`, `Token`: `text`, `LiveUpdate`: `timestamp without time zone`, `CurDate`: `timestamp without time zone`}
	_                 = bytes.MinRead
)

func testOtpLicensesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(otpLicensePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(otpLicenseAllColumns) == len(otpLicensePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OtpLicenses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicensePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testOtpLicensesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(otpLicenseAllColumns) == len(otpLicensePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OtpLicense{}
	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicenseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OtpLicenses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, otpLicenseDBTypes, true, otpLicensePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(otpLicenseAllColumns, otpLicensePrimaryKeyColumns) {
		fields = otpLicenseAllColumns
	} else {
		fields = strmangle.SetComplement(
			otpLicenseAllColumns,
			otpLicensePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := OtpLicenseSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testOtpLicensesUpsert(t *testing.T) {
	t.Parallel()

	if len(otpLicenseAllColumns) == len(otpLicensePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := OtpLicense{}
	if err = randomize.Struct(seed, &o, otpLicenseDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OtpLicense: %s", err)
	}

	count, err := OtpLicenses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, otpLicenseDBTypes, false, otpLicensePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OtpLicense struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OtpLicense: %s", err)
	}

	count, err = OtpLicenses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
