// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPrinciples(t *testing.T) {
	t.Parallel()

	query := Principles()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPrinciplesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Principles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPrinciplesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Principles().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Principles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPrinciplesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PrincipleSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Principles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPrinciplesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PrincipleExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Principle exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PrincipleExists to return true, but got false.")
	}
}

func testPrinciplesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	principleFound, err := FindPrinciple(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if principleFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPrinciplesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Principles().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPrinciplesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Principles().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPrinciplesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	principleOne := &Principle{}
	principleTwo := &Principle{}
	if err = randomize.Struct(seed, principleOne, principleDBTypes, false, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}
	if err = randomize.Struct(seed, principleTwo, principleDBTypes, false, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = principleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = principleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Principles().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPrinciplesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	principleOne := &Principle{}
	principleTwo := &Principle{}
	if err = randomize.Struct(seed, principleOne, principleDBTypes, false, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}
	if err = randomize.Struct(seed, principleTwo, principleDBTypes, false, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = principleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = principleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Principles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testPrinciplesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Principles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPrinciplesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(principleColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Principles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPrinciplesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPrinciplesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PrincipleSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPrinciplesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Principles().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	principleDBTypes = map[string]string{`ID`: `integer`, `Principle`: `character varying`, `SbjMatterIdxId`: `integer`, `UpdatedAt`: `timestamp without time zone`}
	_                = bytes.MinRead
)

func testPrinciplesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(principlePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(principleAllColumns) == len(principlePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Principles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, principleDBTypes, true, principlePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPrinciplesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(principleAllColumns) == len(principlePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Principle{}
	if err = randomize.Struct(seed, o, principleDBTypes, true, principleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Principles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, principleDBTypes, true, principlePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(principleAllColumns, principlePrimaryKeyColumns) {
		fields = principleAllColumns
	} else {
		fields = strmangle.SetComplement(
			principleAllColumns,
			principlePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PrincipleSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPrinciplesUpsert(t *testing.T) {
	t.Parallel()

	if len(principleAllColumns) == len(principlePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Principle{}
	if err = randomize.Struct(seed, &o, principleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Principle: %s", err)
	}

	count, err := Principles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, principleDBTypes, false, principlePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Principle struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Principle: %s", err)
	}

	count, err = Principles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
