// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("BookmarkCollections", testBookmarkCollectionsUpsert)

	t.Run("Bookmarks", testBookmarksUpsert)

	t.Run("Categories", testCategoriesUpsert)

	t.Run("Corams", testCoramsUpsert)

	t.Run("Courts", testCourtsUpsert)

	t.Run("Customers", testCustomersUpsert)

	t.Run("FavouriteNotes", testFavouriteNotesUpsert)

	t.Run("ForeignLegalResources", testForeignLegalResourcesUpsert)

	t.Run("Highlights", testHighlightsUpsert)

	t.Run("HoldenAts", testHoldenAtsUpsert)

	t.Run("JudgementCorams", testJudgementCoramsUpsert)

	t.Run("JudgementCounsels", testJudgementCounselsUpsert)

	t.Run("JudgementPages", testJudgementPagesUpsert)

	t.Run("JudgementPartiesAs", testJudgementPartiesAsUpsert)

	t.Run("JudgementPartiesBs", testJudgementPartiesBsUpsert)

	t.Run("JudgementPrinciples", testJudgementPrinciplesUpsert)

	t.Run("Judgements", testJudgementsUpsert)

	t.Run("JudgementsSummaries", testJudgementsSummariesUpsert)

	t.Run("LawOfFedParts", testLawOfFedPartsUpsert)

	t.Run("LawOfFedScheds", testLawOfFedSchedsUpsert)

	t.Run("LawOfFedSections", testLawOfFedSectionsUpsert)

	t.Run("LawsOfFederations", testLawsOfFederationsUpsert)

	t.Run("Licenses", testLicensesUpsert)

	t.Run("NoteComments", testNoteCommentsUpsert)

	t.Run("NoteRatings", testNoteRatingsUpsert)

	t.Run("Notes", testNotesUpsert)

	t.Run("OneTimePasswords", testOneTimePasswordsUpsert)

	t.Run("Packages", testPackagesUpsert)

	t.Run("PartyATypes", testPartyATypesUpsert)

	t.Run("PartyBTypes", testPartyBTypesUpsert)

	t.Run("Principles", testPrinciplesUpsert)

	t.Run("SbjMatterIndexes", testSbjMatterIndexesUpsert)

	t.Run("SearchHistories", testSearchHistoriesUpsert)

	t.Run("SharedNotes", testSharedNotesUpsert)

	t.Run("SumAreasOfLaws", testSumAreasOfLawsUpsert)

	t.Run("SummaryRatios", testSummaryRatiosUpsert)

	t.Run("Synchronizations", testSynchronizationsUpsert)

	t.Run("Tags", testTagsUpsert)

	t.Run("TeamLogos", testTeamLogosUpsert)

	t.Run("TeamMembers", testTeamMembersUpsert)

	t.Run("Teams", testTeamsUpsert)

	t.Run("UserPictures", testUserPicturesUpsert)

	t.Run("Articles", testArticlesUpsert)

	t.Run("Dictionaries", testDictionariesUpsert)

	t.Run("FormsPrecedences", testFormsPrecedencesUpsert)

	t.Run("Indexes", testIndexesUpsert)

	t.Run("KeywordRankings", testKeywordRankingsUpsert)

	t.Run("Keywords", testKeywordsUpsert)

	t.Run("Maxims", testMaximsUpsert)

	t.Run("OtpLicenses", testOtpLicensesUpsert)

	t.Run("Publications", testPublicationsUpsert)

	t.Run("Rules", testRulesUpsert)

	t.Run("Updates", testUpdatesUpsert)
}
