// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserPictures(t *testing.T) {
	t.Parallel()

	query := UserPictures()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserPicturesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserPictures().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserPicturesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserPictures().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserPictures().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserPicturesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserPictureSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserPictures().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserPicturesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserPictureExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if UserPicture exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserPictureExists to return true, but got false.")
	}
}

func testUserPicturesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userPictureFound, err := FindUserPicture(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if userPictureFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserPicturesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserPictures().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserPicturesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserPictures().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserPicturesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userPictureOne := &UserPicture{}
	userPictureTwo := &UserPicture{}
	if err = randomize.Struct(seed, userPictureOne, userPictureDBTypes, false, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}
	if err = randomize.Struct(seed, userPictureTwo, userPictureDBTypes, false, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userPictureOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userPictureTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserPictures().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserPicturesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userPictureOne := &UserPicture{}
	userPictureTwo := &UserPicture{}
	if err = randomize.Struct(seed, userPictureOne, userPictureDBTypes, false, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}
	if err = randomize.Struct(seed, userPictureTwo, userPictureDBTypes, false, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userPictureOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userPictureTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserPictures().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testUserPicturesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserPictures().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserPicturesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(userPictureColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UserPictures().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserPicturesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserPicturesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserPictureSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserPicturesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserPictures().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userPictureDBTypes = map[string]string{`ID`: `text`, `UserId`: `bigint`, `Base64`: `text`}
	_                  = bytes.MinRead
)

func testUserPicturesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userPicturePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userPictureAllColumns) == len(userPicturePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserPictures().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPicturePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserPicturesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userPictureAllColumns) == len(userPicturePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserPicture{}
	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPictureColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserPictures().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userPictureDBTypes, true, userPicturePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userPictureAllColumns, userPicturePrimaryKeyColumns) {
		fields = userPictureAllColumns
	} else {
		fields = strmangle.SetComplement(
			userPictureAllColumns,
			userPicturePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserPictureSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserPicturesUpsert(t *testing.T) {
	t.Parallel()

	if len(userPictureAllColumns) == len(userPicturePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserPicture{}
	if err = randomize.Struct(seed, &o, userPictureDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserPicture: %s", err)
	}

	count, err := UserPictures().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userPictureDBTypes, false, userPicturePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserPicture struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserPicture: %s", err)
	}

	count, err = UserPictures().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
