[psql]
    dbnamea = "lpedia"
    hosta = "localhost"
    usera = "postgres"
    passa = "pass"
    sslmode = "disable"
    dbname = "lpedia"
    host = "legalpedia-1.cohgjx9vfwbm.us-east-1.rds.amazonaws.com"
    user = "postgres"
    pass = "lpDeMityat9078"
    whitelist=[
        "Teams",
        "TeamMembers",
        "TeamLogos",
        "Notes",
        "FavouriteNotes",
        "NoteComments",
        "SharedNotes",
        "NoteRatings",

        "AreaOfLaw",
        "articles",
        "Bookmarks",
        "BookmarkCollections",
        "Categories",
        "Corams",
        "Courts",
        "Customers",
        "dictionary",
        "ForeignLegalResources",
        "forms_precedence",
        "Highlights",
        "HoldenAt",
        "indexes",
        "Judgements",
        "JudgementPages",
        "JudgementCorams",
        "JudgementCounsels",
        "JudgementPartiesA",
        "JudgementPartiesB",
        "JudgementPrinciples",
        "JudgementsSummaries",
        "keywords",
        "keyword_rankings",
        "LawsOfFederation",
        "LawOfFedParts",
        "LawOfFedScheds",
        "LawOfFedSections",
        "LegalUpdate",
        "License",
        "maxims",
        "OneTimePasswords",
        "otp_license",
        "Packages",
        "PartyATypes",
        "PartyBTypes",
        "Principles",
        "publications",
        "rules",
        "SbjMatterIndex",
        "SearchHistories",
        "SumAreasOfLaw",
        "SummaryRatios",
        "Synchronization",
        "Tags",
        "updates",
        "UserPictures",
    ]
